name: Build, Test and Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Current LTS version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build --if-present

      - name: Run tests
        run: npm test --if-present

      - name: NPM Audit for vulnerabilities
        run: npm audit --audit-level=moderate
        continue-on-error: true # Continue even if vulnerabilities found

      - name: Snyk Security Scan
        uses: snyk/actions/node@master
        with:
          command: monitor
          args: --all-projects --detection-depth=6
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true # Must be after 'with' and 'env'

      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'My Project'
          scanPath: '.'
          format: 'HTML'
          failOnCVSS: 7 # Fail if critical vulnerabilities found
